function [emptyAccount] = createEmptyAccount(...
								name)

	% Definition of structure "performance".
	
	emptyAccount = struct(...
		'name',					'',...
		'year',					[],...
		'month',				[],...
		'day',					[],...
		'balance',				[]);

	emptyAccount.name = name;

	return;

end

