function [emptyStock] = createEmptyStock()

    % Definition of structure "stock".
    
    % Each field is a matrix of values
    % corresponding to the different
    % data for the day described by the
    % "year", "month", and "day" matrices.
    
    emptyStock = struct(...
    	'name',			[],...
    	'symbol',		[],...
    	'exchange',		[],...
    	'currentPrice',	0,...
    	'year',			[],...
    	'month',		[],...
    	'day',			[],...
    	'high',			[],...
    	'low',			[],...
    	'close',		[],...
    	'volume',		[]);

	return;

end