function [exchangeMatrix] = createExchange_02(...
								timeStamp)
	
	% Create theoretical stocks.
	
	% This will create a list of
	% theoretical stocks with information
	% about their behavior.
	
	% Create theoretical stocks and add data
	% to their structures.  Create a
	% "stockExchange" matrix to store a list
	% of all the stocks theoretically available
	% for purchase.  Each stock in the exchange
	% will have

	% This code will create 5 imaginary stocks
	% with a range of share prices.  The
	% stock exchange, timestamp, and trading
	% volume will be the same for all the stocks,
	% since price is the focus of the simulation.

	exchangeMatrix(1) = createStock(...
		'Stock_A',...
		'AAA',...
		'Exchange_01',...
		50.0,...
		timeStamp(1),...
		timeStamp(2),...
		timeStamp(3),...
		51.0,...
		49.0,...
		50.0,...
		10000);

	return;

end